jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:mtk9wwU1AaU447N/8V64G50=,iv:QK1l8diCp756mHnFgyHrBi8gAwX/YHTkWZRBVbKsle8=,tag:O5c35Ug4csyqJZLxqRnyBg==,type:str]
                client_secret: ENC[AES256_GCM,data:Qv7c420euPLHe0YX46tEMjtVAnKYaGR/Q4rnk3ABE8q5zvXqkTzcDQmt9S+b6alzQo6Bxqb6dm7xYSX7lWvCNQ==,iv:zK7Lc+hYPSA8AuFjzm3xYxOAa+12/fXAE8cSIcNKygM=,tag:S8+5nKLf0KsN2FKIzSNr7A==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:Bb2ormdp/Gv7KJY8uo2RY9Akbja15EK2LiS5wyK50Jcag8UM0Qgmawrl/xOLVHUgmkEQ0nVoQg==,iv:1euT0iRG3p8ubgHN7Ur9zCrXsJefQw+D5y6yN2SaOw4=,tag:yFM5rPeW5V/5A1qCLNZAWQ==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:DAFO/HuslEWqh5xD,iv:7UvnJyHC7t8s7xB8IoVzM9RkrX4Qzqmy+AE67j/3yB0=,tag:p+whCthljo7puGF3r7MgVA==,type:str]
                command:
                    - ENC[AES256_GCM,data:crhhUvXQTOzXik5C,iv:+m9ZRsB/4CdCqSF21dYJXxatVIH/FFWMFW5OWIofDmg=,tag:yPFXXvPSxtrxAPDYFNLUCA==,type:str]
                    - ENC[AES256_GCM,data:JkKgGnWNUR0n3kStuQw3pPJa61CRvufRLsk=,iv:biaHHeYanaXpkXF75VKa48Y2flKN+MpZlSH/RtBEA6E=,tag:orvSNdKX72veJOYQCp8+vQ==,type:str]
                    - ENC[AES256_GCM,data:n4F7UDvXnSYJHOV7mkkjjt5h/FB/iIkL/1hXBafTq2Q=,iv:aVH7Sq3KtUyzits9q6u8AZzEvKn/hJKFG4/Es9xmN3c=,tag:W/6Ev7QAlxYRKu0p3jBR2Q==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:38:08Z"
          enc: CiUA67O9AGRfqIW1IuoOhhhNrh6L0sLPObA2U01YEmtBUanfW4ifEkkA1heVYb6mcW7y4nGUFS234Irc9TKatxz+PtoG8Lp9YI9rHZr/gYc19mRMW5fs1pz7RcPM493hRuEKyALtm2AyV+sxx+sEAvwu
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:38:08Z"
    mac: ENC[AES256_GCM,data:xucHNpD2K9LHOOBKmb1sxDFEHXmkea2JcW6Im1DoCuruNu3YvjPEQwzFKgm9ft9aNqK0je8tKjq8qZMS/bahrg7kvMgdCmu29ASywNnDz4DcG/DnPG/qzeN/jIlIe2HKwZ3NdaiXV546EJ3guCy7lRFLu9lBDCbOnkGAocNwP6k=,iv:OzyVXTeC4UYSyaryOiPLGSMTpWD2PEXAXsm7dzh4dbQ=,tag:iMmma4uSFff8rW28qXUToA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
