jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:14xPC/ZAM9a773JmVe5D6qc=,iv:3nsEXQDbEVa7vz8JTfiFX5igeyPhOC7rWgJuTssc3wg=,tag:tYowzTsJcR9XIR/cUEDcBA==,type:str]
                client_secret: ENC[AES256_GCM,data:dJ7EZdJmJZfKJIOy4CUBGrhTdpqHrvJsXRQbMSeqq4BmrcYATaeWm6fE/zt8+tuEcZIcyJoyFcyXayP+Hr++9A==,iv:CoE7iweg2j9B3jz/p8RRAgIMwiIzcrwtHzY0KD2T7L8=,tag:U+dnlhz8O1miyMAZi/YkNQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:U7ghit5WOsxPdmSbmwyweL5Acx0hMZC4eviKQSVpc62UFTUMVS7QibdaCF6Z8RCW/m7UmWY4,iv:URK8PM1NQnwZ2sNv40ta1Z4F3FgY+fUb5A3S9+q1gEc=,tag:5UrytTGa82QB7i8fYiQYpA==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:hSA6UL8BHTG76479,iv:8XvxiM3z+QjVqjQC98I+pl43Xx6Kf7nd3n8+Mn+hI6E=,tag:tV+8ApBRRXyjhrDs15fvuA==,type:str]
                command:
                    - ENC[AES256_GCM,data:R+S4iMWUI6qyjMO/,iv:anmP8KllrmJ1hr9kuv9KEepiEGaJ348Z4B6Ae26N/+g=,tag:hlev5jRIdI4KPqfgsPKkKg==,type:str]
                    - ENC[AES256_GCM,data:gkwdPx/RdsTVB7OYgkiUyop98YtXndW/zA8=,iv:JD4/R8tiRN9T8z1zlFw6ux1nUAzsVYHlYFY+m3S4cvQ=,tag:rQ3LpeJ89v1CB9rZ/0upbQ==,type:str]
                    - ENC[AES256_GCM,data:BSqLsHQr11uhWa4vfsitkhe8aHtRo+0RlPwYWysS1l0=,iv:nOwQLBcMuQ4SbR8Qvra53IC+wvg2OgAgfVKhyVzK3V4=,tag:+Qa9WgW9gdxiQSxG4Ly2OA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:40:00Z"
          enc: CiUA67O9AI8b9hABeyS56rjvTb5ip+eGhHuf3NBt1ntJ9ydTMwg3EkkA1heVYZ1yg2RYSBdmejvp9Okbszo77La+F2YdTlloR4e+wWy+7pDKQ7bNKOoLTmq/tOuBHClWKg4dRumFWjRe7AFavoJa0TlR
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:40:00Z"
    mac: ENC[AES256_GCM,data:gOzsXOQJ6bQsBkE6vSCjWSf7R/Wb4qcfPGfibdpBpxQMlOiXGyvH+xDE6b+yCnkwg/7RQmLzzg+1ys+bnmdgcFOR+XvuoIFSUgZLcle6illWnfoGvSfzcocXlpB7pywkZqbo5CNLrnMdPig9sv4nspPYCGtDpLFHDAvXx4UV5tk=,iv:Qv3Kts3VcxRb26u1DLQwPiI16IdV4mNF44o3GF9XS5w=,tag:TV8GSafX7zTHjG/00neGkQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
