jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:IGfcapo5CrXgDREVdmnLH1g=,iv:9dzOs4MTvgWYnwfAwubLewvV/t9xILAnBWcrblYX6DU=,tag:CvT+kzCAkTPr5yDG4gVwGg==,type:str]
                client_secret: ENC[AES256_GCM,data:5j0q7vIAsRRmRxWqDTCz86+8pkqMkqdfkDYojtmATlPMemDiI+fbo3TylAcw0TeGk7JRGDsOZf0jmFNHTe7CtQ==,iv:maEvUxM2LB41PApQRs9GPQuMLOq7fzGDvrJGLDOuxN4=,tag:mTgPbvFZc83kBXhCkieAKQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:hSPfUiYvLbkgztx/OatrPMSGU5g0pViW83O306NSPJ0SOKqr+z0aHiIUCctSDGKge5ptpxc=,iv:lvK3TvI8djZpEZKQDkvNe1gIMzJh4PkoiJVKDld7KT4=,tag:n6S3t0/hckqNWx6V0HOvrw==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:PyfOBcJmSjizZ/2a,iv:0HRakfUT5q1Tjk1xD+RHcbv3ewhlbdAqXNJ0ED8JxP8=,tag:ms9Yp7MgPvsXjcXaMr5+uQ==,type:str]
                command:
                    - ENC[AES256_GCM,data:w7DSD2Qp/O8t46bb,iv:2PLefPIsdP9k2wkKdy3RaL6Lyxv98wxn5jZ+idaeXqk=,tag:QSnDZaEFb31DrFWjP6ChEQ==,type:str]
                    - ENC[AES256_GCM,data:Wsd8yGwafBHA41kpZHi+R3rCJqGjuYe7Edw=,iv:ADgVOHHpx51juX4fpYv6hEpK4ddQp2vlvw3aNCPXEB0=,tag:YQAL83NiC1fdQ2/OcMsYrw==,type:str]
                    - ENC[AES256_GCM,data:wOy0SKCkmk1DOI0kqUad4ZmYKEZKlgQaPin/6F4fyhI=,iv:ed0TPpyTlwjICvVQPO886yC9DCYq+pkajeSpKPdi9p4=,tag:MZ/8eL7qZGCnDuOaIuwTaQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:31:36Z"
          enc: CiUA67O9AHFYMGslBVEbCcHIafcX3ql3g/QvhiVLQsGGph4lvQj9EkkA1heVYSMvN4QDR6ewrPyCI5oIvRdHUxwiv/FbVo/pJSYjaTWWpK8Z4SuKil9xUzOFrID5aAGQeB6X/Jhu3lJnO71GBHimp+BM
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:31:37Z"
    mac: ENC[AES256_GCM,data:n7bRAbID6LWQnT6QcKaGjvmSaycf5/ZRdH1thq/Wzi1wIJK29+Dx63qY4SkjBeprOJUzmtPvzWxR3sUPSOCFHmWTYEUET74ye+3/BlkAp/UTkHXjcBgu71SueFvm8YoNQw1BEML3SLPuzTBFppsuy4YMK9/ncxzl/lENrju8dVs=,iv:JCMQKc9LCE2n5a++Uj19OSNC2xW1ErFfAh4ocV0vjWI=,tag:PkejD3AuZkWS/b89qTUHww==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
