jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:YvRdKrRQpky4ZqDTqtPlro0=,iv:lro3OOudkKxrRZ7Eze8eO4H4eMRxmYkXQGBzDJuAm/s=,tag:zFw/cET7YmEBYAzOk5rIzw==,type:str]
                client_secret: ENC[AES256_GCM,data:wiJ5PdhsGmCn4dO7458ovExGYPpsWywhrBAq44XykgXVJ7pziDYuROEQfqJdC3mX7uswPopz9LFKQfUbaCFFpw==,iv:XgBPaXQYef7puFT7fntRNLXE06OYAEjJPuXeOflwAo4=,tag:xp6x+y0b8jvV2SLCLXuBeA==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:wAvQK+Cuo57PZT6Co942TPPUQITVdIqPN6QV9wHWT+b5O81N0cIPzKlbxDyak6pstV+utavPyQ==,iv:I1RQbFSj+/swDU1PafaD/Vnu/y8Q1o0Y0Sy7OArDH5s=,tag:0juuDhjQcstyQp6Y4UR53A==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:CSnANIKYL3C4jzai,iv:6vKhwDkB1HPE1bGaf4vzuTS6FMgNN6+EeeevH3ktin0=,tag:Htj+9zxdBzCGVMWIEJTmQA==,type:str]
                command:
                    - ENC[AES256_GCM,data:5Fom9uFaKS5WTKmj,iv:VbFegKFcpOP1Nt4o1gBdNkussVTNta6xp3Y9yTKlmfc=,tag:SBi7XyXeJMbvbDU9enLfEg==,type:str]
                    - ENC[AES256_GCM,data:/5VVxpmTyItsr2Li4KjC7NWEqmoyHkNMx1E=,iv:YL4O6t7yk6zHTgb5eSj1krY8QCadS79aFkERHAEcoow=,tag:KT6e9kcmLbeEeV0w1/U+pQ==,type:str]
                    - ENC[AES256_GCM,data:l5YhOocHQbB3gle/5sVg8KWoWqsJEcZX8QT8AKV2UFI=,iv:D9lTqwfZUVy69ZaaQgpmZWOmLsLHkqIkCIAIl5O50sg=,tag:QJz1jNKVB0Kczu+H8iLlHQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:33:57Z"
          enc: CiUA67O9ACq1YUzmCO6zKrsU0U9aJwhnCAiq6zyy+OPYGbB0RNkgEkkA1heVYXze2tnPC3DP2SYQstPyjTDd2RhtcD1BUqGLOH1KozrhRmOUMHF0jXXcMufLqWENiJDE5q0kTKiU9vc0KSRTL63ZdYH0
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:33:57Z"
    mac: ENC[AES256_GCM,data:n/HDU2+LLYw4pHVkPsRlOa5aMtHw6WDWfiVdsaUHDDpjFyY5HA3duw9TerQdwirmpHiFBkq0MA1D4mqOEpAKDvrfzFsl2ORWYQXE63h75zhvGmeU2SLHLf7rb8zSJcwXFE2Eok2kjdRt5ZrfBZDt7pHUpkBXhwegh9E3nqk4q/c=,iv:jPXO2Qral8gEMg3blSr9JMK8/RPB4vMvpoQ1p2q7M7Q=,tag:X4JVXn7+XfMJoQVtNYkFNA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
