jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:Z/5UtvHvYChgQ3SbNZr/JGA=,iv:+9oI2JpZh0x/dL6uMSasgPc/fABs/vwa495z9bWAfD8=,tag:kRU0E80djvG2F95F9TlVoQ==,type:str]
                client_secret: ENC[AES256_GCM,data:39qUfbKM3428r9ecux2ionR243/GwOA30N57ftiTj9L4MIhq9GVLRWL2Rd8NIaFamHM5zITbDJOAayosM8m+Rw==,iv:BAcmVaLjE5qyjNWW7s86wL8DPR5yDrEzure7L5jyS9w=,tag:Hz5eLkHRbC3iamzswQfaOQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:ozGghX3eZW7Vb7/4WaTSvOvIAj4iqS0E7msm/BDI5ZsBVT2pYm2KvOTc51HWeN4TfLb0X4/R2Q==,iv:Y16o3+vvMxhuvDrcXa+6tdzB3261MR7su9O8O0nJCEE=,tag:Y979bcxa/8quI0BAmd3Z6g==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:St7PALMFIFyqpJYx,iv:YhmBT1unbUDlCwmrSSnMf+jUhcV/AMaB0R+5B/aQNus=,tag:xic/zu0/8T5cNUBc+PEpBQ==,type:str]
                command:
                    - ENC[AES256_GCM,data:85N2EUG5BfAc00ZM,iv:Azp1l0CFZo0eR/qm6sXXZGs1j4T/Spmo8eY/iQigx58=,tag:sputf5cvZbctTaOG8Afs/w==,type:str]
                    - ENC[AES256_GCM,data:aPvPIYA9YGUzL3+NuvnQ1na7mCBRxbRAsAc=,iv:gbME/YsrY6aP/cBQAi17tCLMzOEQoRxTPdb+r6BNmnE=,tag:bfp//MpZCM+owCU2v0rOdQ==,type:str]
                    - ENC[AES256_GCM,data:XiZyFTYTEXI6gOGb3RR1qrAZX0nDFBXY0269fT0Qfuw=,iv:415Usxb3JFrjLmxkGNvxKfSfFm50I4FkuJmySNsdQcg=,tag:r5OHlnceudthZ4KsXQeU3w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:33:39Z"
          enc: CiUA67O9AM/FFx/SQH/umey66QdZihr3hYajaOrmUUct/ecbMRHqEkkA1heVYdlCuJDCYxSqGrKMf6/hWWAKLrb0jCpRF440vCTl/lhGWzbLL11LyMzDBlofqE32ixk7mBHirRSGaozxM0LoN7L1sC46
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:33:40Z"
    mac: ENC[AES256_GCM,data:LMTM8SvtR64vYU82T1Jgrphakcsdayr01phljjjSpeo5G90CVtILbqE4hvngGY5aU9qD2OJ2LjR2LwFZ2oQVI1gX1m1FA9y/KAWF/FzR9uNTQuaDrAftSEP0+kWvebIZ2IZjSSHhvHLLHctykh+qvxvuExNNXbt/Yrd8fCBd+00=,iv:JDu6AK4YU8JmKkHgSFLFWejHiTHQj1TEkUu/ETiTHCw=,tag:BvXTYyNFdPzlf6i977e5Kg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
