jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:nlSbTng/jJudnNKR+swZH1Q=,iv:Br/+3luxL3V1KyFMQy+U6EgCN+MQ34TppIbgfBMauCM=,tag:ITPsgOISH4cgLwWRIy5AKQ==,type:str]
                client_secret: ENC[AES256_GCM,data:pLW5rTfRvoy8mKfFenQVRjc8KQik3+oqzrCgcqiD0SARIHtGL2pq/tTwwqGkfrsz/wWgS+WePYrbo6+ak8SDXQ==,iv:YErJbmG8AmX2slHRjd3BfNyVFmosucIUI7OATuuqjFM=,tag:dnzwq0+kSy0JipCv0uATkQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:0H8FgwYhbTrI1fu1T9TQ5xeLhKUEFo7aO4FwzDMjf2Ovctca9OYaHxCSJKulSnddNFVCGPmcXQ==,iv:5ETTfBSdKshWp5sqXKn43uzUVeYTHAegkR0ezxrWx4U=,tag:V/Iaq8jlZn6S9tCyF/FtIg==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:PbHFceuW/N82zmtc,iv:KTnsEwx9gPSVOssZEjgamTi66/JHMDAM+OLfdv/Oqh4=,tag:MqP6cWKMavEOCwoarLDUoQ==,type:str]
                command:
                    - ENC[AES256_GCM,data:+LE3RV0Ok+YinxvG,iv:9qaQjJMSWIaPB7EecBUougC/dQvehVkF4S+p+EQCfmc=,tag:jVGxRDVs0paRvvojt42z2w==,type:str]
                    - ENC[AES256_GCM,data:sShnmqffHK6hp/k8oGkB7YevdxoTKPG7wmM=,iv:MHl5zpxmP/Y7GrjRvDbrOWnRWSUBehxPpSho53Y+3tY=,tag:FoBeL/byUv/H0By1oTNFuw==,type:str]
                    - ENC[AES256_GCM,data:jFhglq1yqa8nUzFPnCEHkYz4A2Hap5zEEE+lD99NLxw=,iv:yUWQAw2bb75Prxh8FbCUqfb6z+3xvXZP2t9kpXijGlo=,tag:bAQRHdHet20kQvvw7wqghA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:38:45Z"
          enc: CiUA67O9AE7eyNGshNuAMWykc6ZQT4QkOEghjAl+EZHuUR/f1zhaEkkA1heVYfoJvOpXS85x0ASFaYF2I8sFdRbwWQ9flcvkc+64+t44jsU8gj0ZxxGTTd8JEGeap4oiHGFhQGvU7pvHqzwreGVqCYss
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:38:46Z"
    mac: ENC[AES256_GCM,data:zW9lSbx4pETxTbJE7qpABs1KT0pUtdbJeVwlliAgDMEKbzI0rdGjnCQzWe3S7BXR1LZcsI4SVJ1NgPJ+QVDm30YyYB3VhguJIPJHIDVFfd8UfvhLOVkWMlgbFlT/WGnhuy82iGbE8QKxNDAHIL8ii1MfytCoHfAvHTRwfxn6hVQ=,iv:e0cGDJRihrDkDfEoLiJ7mH1Y2iTxYqg9Wbp70eyYIvo=,tag:aASteLH4znyiTj46oD/9/Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
