nfsPVC:
  nfs:
    shareName: shares/stat159/prod

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - stat159.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - stat159.datahub.berkeley.edu
  hub:
    loadRoles:
      grouper-sync:
        name: grouper-sync
        scopes:
          - list:users
          - read:users
          - admin:auth_state
        services:
          - grouper-sync
    services:
      grouper-sync:
        name: grouper-sync
        environment:
          JUPYTERHUB_API_URL: http://localhost:8081/hub/api
          GROUPER_BASE_URL: https://calgroups.berkeley.edu/gws/servicesRest/json/v2_2_100
          GROUPER_ID_PATH: edu:berkeley:app:datahub:datahub-stat159-users
  
  singleuser:
    storage:
      extraVolumes:
        - name: conda-shared-instr-prod
          persistentVolumeClaim:
            claimName: pvc-stat159-conda-instr-prod
        - name: conda-shared-stud-prod
          persistentVolumeClaim:
            claimName: pvc-stat159-conda-stud-prod

  custom:
    group_profiles:
      # DataHub Infrastructure staff
      # https://bcourses.berkeley.edu/courses/1524699/groups#tab-80607
      course::1524699::group::all-admins:
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1524699-readwrite
            subPath: _shared/2025-fall/courses/1524699
            readOnly: false
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1524699
            subPath: _shared/2025-fall/courses/1524699
            readOnly: true
      course::1546508::enrollment_type::teacher:
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/shared-readwrite
            subPath: _shared/2025-fall/courses/1546508
            readOnly: false
          - name: home
            mountPath: /home/jovyan/shared
            subPath: _shared/2025-fall/courses/1546508
            readOnly: true
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1546508-readwrite
            subPath: _shared/2025-fall/courses/1546508
            readOnly: false
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1546508
            subPath: _shared/2025-fall/courses/1546508
            readOnly: true
          - name: conda-shared-instr-prod
            mountPath: /srv/conda/envs/shared
            subPath: conda_shared/1546508
            readOnly: false
      course::1546508::enrollment_type::ta:
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/shared-readwrite
            subPath: _shared/2025-fall/courses/1546508
            readOnly: false
          - name: home
            mountPath: /home/jovyan/shared
            subPath: _shared/2025-fall/courses/1546508
            readOnly: true
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1546508-readwrite
            subPath: _shared/2025-fall/courses/1546508
            readOnly: false
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1546508
            subPath: _shared/2025-fall/courses/1546508
            readOnly: true
          - name: conda-shared-instr-prod
            mountPath: /srv/conda/envs/shared
            subPath: conda_shared/1546508
            readOnly: false
      course::1546508::enrollment_type::student:
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/shared
            subPath: _shared/2025-fall/courses/1546508
            readOnly: true
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1546508
            subPath: _shared/2025-fall/courses/1546508
            readOnly: true
          - name: conda-shared-stud-prod
            mountPath: /srv/conda/envs/shared
            subPath: conda_shared/1546508
            readOnly: true
