nfsPVC:
  nfs:
    shareName: shares/stat159/staging

jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - stat159-staging.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - stat159-staging.datahub.berkeley.edu
  
  singleuser:
    storage:
      extraVolumes:
        - name: conda-shared-instr-staging
          persistentVolumeClaim:
            claimName: pvc-stat159-conda-instr-staging
        - name: conda-shared-stud-staging
          persistentVolumeClaim:
            claimName: pvc-stat159-conda-stud-staging

  custom:
    group_profiles:
      # DataHub Infrastructure staff
      # https://bcourses.berkeley.edu/courses/1524699/groups#tab-80607
      course::1524699::group::all-admins:
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1524699-readwrite
            subPath: _shared/2025-fall/courses/1524699
            readOnly: false
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1524699
            subPath: _shared/2025-fall/courses/1524699
            readOnly: true
      course::1546508::enrollment_type::teacher:
      ## Course Name: bcourses-1546508 Bcourses ID: 1546508 End Date: 01/01/2026
      ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7407 for details.
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1546508-readwrite
            subPath: _shared/2025-fall/courses/1546508
            readOnly: false
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1546508
            subPath: _shared/2025-fall/courses/1546508
            readOnly: true
          - name: conda-shared-instr-staging
            mountPath: /srv/conda/envs/shared
            subPath: conda_shared/1546508
            readOnly: false
      course::1546508::enrollment_type::ta:
      ## Course Name: bcourses-1546508 Bcourses ID: 1546508 End Date: 01/01/2026
      ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7407 for details.
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1546508-readwrite
            subPath: _shared/2025-fall/courses/1546508
            readOnly: false
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1546508
            subPath: _shared/2025-fall/courses/1546508
            readOnly: true
          - name: conda-shared-instr-staging
            mountPath: /srv/conda/envs/shared
            subPath: conda_shared/1546508
            readOnly: false
      course::1546508::enrollment_type::student:
      ## Course Name: bcourses-1546508 Bcourses ID: 1546508 End Date: 01/01/2026
      ## See issue https://github.com/berkeley-dsep-infra/datahub/issues/7407 for details.
        extraVolumeMounts:
          - name: home
            mountPath: /home/jovyan/_shared/bcourses-1546508
            subPath: _shared/2025-fall/courses/1546508
            readOnly: true
          - name: conda-shared-stud-staging
            mountPath: /srv/conda/envs/shared
            subPath: conda_shared/1546508
            readOnly: true