nfsPVC:
  nfs:
    shareName: shares/stat159/staging

jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    enabled: true
    hosts:
      - stat159-staging.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - stat159-staging.datahub.berkeley.edu
  
  singleuser:
    storage:
      extraVolumes:
        - name: conda-shared-instr-staging
          persistentVolumeClaim:
            claimName: pvc-stat159-conda-instr-staging
        - name: conda-shared-stud-staging
          persistentVolumeClaim:
            claimName: pvc-stat159-conda-stud-staging

  custom:
    group_profiles:
      course::1546508::enrollment_type::ta:
        extraVolumeMounts:
          - name: conda-shared-instr-staging
            mountPath: /srv/conda/envs/shared_conda
            subPath: conda_shared/1546508
            readOnly: false
      course::1546508::enrollment_type::teacher:
        extraVolumeMounts:
          - name: conda-shared-instr-staging
            mountPath: /srv/conda/envs/shared_conda
            subPath: conda_shared/1546508
            readOnly: false
      course::1546508::enrollment_type::ta:
        extraVolumeMounts:
          - name: conda-shared-stud-staging
            mountPath: /srv/conda/envs/shared_conda
            subPath: conda_shared/1546508
            readOnly: true