jupyterhub:
  scheduling:
    userScheduler:
      replicas: 1
  prePuller:
    continuous:
      enabled: false
  ingress:
    hosts:
      - cdss-discovery-staging.datahub.berkeley.edu
      #- cdss-discovery-staging.nrp-nautilus.io
    tls:
      - secretName: tls-cert
        hosts:
          - cdss-discovery-staging.datahub.berkeley.edu
          #- cdss-discovery-staging.nrp-nautilus.io
