apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 2025-fall-stellar
  namespace: cdss-discovery-staging
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi # smaller for staging
  storageClassName: rook-cephfs
