jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:/o+EIfdfDKCiUjXMPsdncmA=,iv:7RxYFDxlXfrTAOJn0oLnt5FBemkxr0LozpOhMaA+mHc=,tag:FT22dTRbHYFTylmGAwWm2A==,type:str]
                client_secret: ENC[AES256_GCM,data:STl6n98kVgicbJNoVJTAzxYS8Q1w95vpqBoIv5+8VwWh7XIMwHjHv+u7mvv+xjzpjk8oupnSuO2cVGr5/9N88Q==,iv:+/JUSGK85QqGcu7ret9hQxJyVIIhtcUHfsihOCAhtoo=,tag:ILE7hClJx9dBofnCX4LUzg==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:mNUoe/SQsT+L7/rrAVY4V/CuuRbehXv7hsKts+s4rG/Rls3X7+nqWkZj3nzAl37UNJHKGg==,iv:9pw2b+VDth9zucwwZBovyq/DOcILIzgD8PppFAAANN4=,tag:fgxvYWhwZwY6BIYm3JamUg==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:DarMgzJbF20htLm1,iv:WI2LodeA80fk5Nnz+Eax6HPrSVz31Z9chcXHAAug3NQ=,tag:KfyIFVn0WRfD90U/mo8gSw==,type:str]
                command:
                    - ENC[AES256_GCM,data:xmCJn16+fgF+wKbZ,iv:fw6P9EiAVoWaThw+6Mop5J4IyQsFo2xeijUnR9duSnk=,tag:sywz0St3IVdU2A03wvpnRQ==,type:str]
                    - ENC[AES256_GCM,data:PrzQhEKT4K4pcBgRISfoSpXShOALiJb3Ir8=,iv:zryDOcGri9V3YG8evB20Zp7nU5N75LyW8nwAX2XD7e8=,tag:ubSnf2MMNznCsbGym2uSuQ==,type:str]
                    - ENC[AES256_GCM,data:97gSsBNEAK1dyz7EC41K3233pp+FLsCpW6m5veKzNLE=,iv:H+6UcynzYCLe0PS05WpI7JuQgMFiyHDhhT1g14S0+40=,tag:pFtXRZzfinkMmRDZUfrowA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T22:58:43Z"
          enc: CiUA67O9AM5ZQqw7bEKZ3ut3Z89imE/VLZ3sOygxM5MUx5p6928SEkkA1heVYZPUSPOT/zUKRNFAiU3R9GoBWuvasZWVhWeFg0byE6yOa4erTLnxkRXLV5+MXnjSJlEQ1reVOJAvWmqjJHFNqgOGSgGp
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T22:58:43Z"
    mac: ENC[AES256_GCM,data:LIzk7c5xYGQzLbUFj0hoh9wSFXMrOtP/ZyaK8s6EoqeKb5vvVsV0rLfZzv0c4h0JDJkb4ijQKivwf9gs8AhX46SPrhlH8Sdi2BeBsWNqEl+SZb7OumYGoNHhoom52vWSeN8ry1Ff4aTOr9nlzo0wjkcTf7HgwsIt27Q3UuLZtdI=,iv:lqS9py3WJEOsnVpiq8Y4uDlLqGgMPAdnNLgnNAdCPTk=,tag:fdwgjDCjRs4YkadDIFFJsA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
