jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:YkAitSWzpiEvv96ehBBw83U=,iv:4Tz+aPJB8aKl0IgRW2aweXvu287Ubnfd8argmMMwj7E=,tag:XmNQe/j2tV0HFN07HJg/fA==,type:str]
                client_secret: ENC[AES256_GCM,data:DsgpqvkZ9TgsrfQ/Lah+5LcbkwjbX5RSu8uThKz2tUFQw31Rh3ZMG5ZAxptuFDOrl7AeBJe8/W8lJo69GS4Ndw==,iv:H2Pf+gyAU8pLAScXdq+tx1eFGDy9P4ho7E7S9rXAO4k=,tag:HLxAzPOX4fDoei0Dwc6ffQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:Fix2ak2mwTNowvo4yoPqdhcOvyttvaZseZj4pCMYt86guGTTRYrJsWmCFkb7tnTRHXITygg=,iv:/Rb6wNkkgusx4O6o8zIGhY7Q2YnqyUWsw025mkYRLaI=,tag:IecspvoCWX9bT3OCe3XWag==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:GSnsoc+Tp44NZ0zv,iv:FxVqa+pO7oB1f1YT+QxqQpoYoZOkmsnvS5fdrnEjEBk=,tag:oIZwJPM6qHvu3S8EMqPK6Q==,type:str]
                command:
                    - ENC[AES256_GCM,data:7ZO1ZKeLBXsA6Mfo,iv:IOBfh+6OUCbslesYLShDuFNOSpvRsFM/ycDnsFHVjag=,tag:M2Kgyy9oNyzl7O3RbI9j5Q==,type:str]
                    - ENC[AES256_GCM,data:QKr19zdVUZ+2qPwFnhCmuGVwiorFJsnxCxA=,iv:vB3rnKC100hqdvdCaB8ypXIzFzjeARi273nm83RExG8=,tag:66zAXwrIF5U5gCn4p1oq1g==,type:str]
                    - ENC[AES256_GCM,data:JBQR/yOkMz6bY7tHVrxTblyr2K7tiNkzVte08E6n5Sw=,iv:iz0xQqDDpiF7da+ekshhF6cBGCw3gXz7hvSgMWdWIu4=,tag:sTTsYIY1I2F9aexr/dwjaA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:40:57Z"
          enc: CiUA67O9APMJs56D/43MOCxk/D48qMrElWwYiHMCTWtaVhfkJ8c0EkkA1heVYVK/3qNIXSdC13DW3+zOas6T5E3Mu/TJEL3qiMKACSB/Bv3dLNVhqTvJTT+VbbIpkyWtKB9RPkpvxZ7XqtddLKZmvw3G
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:40:57Z"
    mac: ENC[AES256_GCM,data:Yb9ktCnP250vvR43If4ggtaMJP9ezibFcmJx57B4Ub6dfuxwgoOyr8jOdz/LWc2NnHOAdhpqUCUN0FjIVsc2HnU4h6f6iki0RMgTRLSYRc4UP4rk2UOXEXiwz5ahSeCW8ZNqkGp4zFNCi+LIw+adTlnprJYAroFyDmJ7dsXyPSQ=,iv:wZq3gT81yqD+E468NVRQWyDd6pJF9FpHRh1oSylXwQ8=,tag:0AgJqa9L7uUpLZtvPyQQ8Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
