jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:J8crkjAgr6rW0edxbSccuJA=,iv:5jv+iM8F1AUe5iCN0kw+eW5PJa6qB3HToSQJwFW175c=,tag:pIMYPDR2PURUs5yhJY77eg==,type:str]
                client_secret: ENC[AES256_GCM,data:EGEGMvfPuW8wkhjqRXD7gkkvxwujwtcuLWjL4Vr5V5x09iXO7dJlM4r3a2PLkakrnk/ZWz1ztCsVgtD7qDMVdA==,iv:XN6TjgdWkU7pIe/3KuEaIHukZpZevyqrveb1CzxZ40M=,tag:DsztL8AQVt9KDL+tm/CleQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:HsqRUwns6mzJf4OHHtqsXF+yWqjLNG1j31Sh6sNJfPrLGWQBHo4/0Ag637MPZ8uGtYPfq/7R,iv:QcCin+HxPZy50nng09iTghEzawtN+a+/BBr8kIpc4QY=,tag:hC7pZCgwdpOpcKcc7znT6Q==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:CUHdveD8jGMD0Kax,iv:+BOzncYlNW/10A6mq+BgTzyFBCfRyb9IF/Rm00mh2Ts=,tag:ejw62IHc9HpivZrw+Cl7iw==,type:str]
                command:
                    - ENC[AES256_GCM,data:UmY8EJoIVsDT3kuG,iv:YuW5rtfFEOdWgg9sWVUU5gxf8RguhXXFAH5wQ3Obzsk=,tag:YuOWRf2YdCdLy2dAX907lw==,type:str]
                    - ENC[AES256_GCM,data:jzxxy7brTgzgyzp4LZ3C6j6ThfXgjRuR4t8=,iv:hb9+KxVuMjMESoAe0keVOzJsqqALIexFbtJwlfA3iCk=,tag:lwsQkZZawI81wWNpFLWbTw==,type:str]
                    - ENC[AES256_GCM,data:3GNZZbRZgCGhBpCqi0AaW48angDpwM5PGXJ/B/KsSIA=,iv:kb6Zuh76RzjxbSo/9Ce2fih8UepZVAd+8AEcl7ZsFkM=,tag:i2xnBnJI+ofpkSy/J/KWCg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:38:28Z"
          enc: CiUA67O9AKANis+7c6yiG87i228FJBLD3omRU8fk251RRn5EHnYvEkkA1heVYRhpWYU9h+C5spxlcytLvmx1YFyPR1TMGNOhbUkPNP5fpOlE/zB8m8ghMZpEfFFEYPx7BIi4WqCZjUJQdPDh9mo+TfP/
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:38:28Z"
    mac: ENC[AES256_GCM,data:MHr9mzJoqFTAcJ6mpAR7jsBtEnWpzdn2xQGxzA2gqKL7T4pWHN6x9f6ZIrzH7sxy1a7nFR2e1pOgUWYbb8520W+64a0AQrHJTuPagUiyAlfHXCTzm/2mAINSPXEXyFeygbtZoSaNcUAtwVtMbFmdRL/3hC1TeL+7kpa+eDTnbsE=,iv:ZRr2uyIBtVFzk7Ar1K2SOk6aN2aUR6fraGQUwnoepMI=,tag:4InNAS1GwGCcxNjhd/HfCQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
