jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:l0Dr+cg+eFMLbu86+F58fs4eCKfPvriAnZD4tfCiBnNMY+ea+KgPNPMW0ZpdFgx41LrCgQJileDFaMfVd0aDbUn4PggaLwdt,iv:VohhlgvYwS4COMZ0cDx4j7OmCdF9mWQNaU4s8pFAnhw=,tag:dX5/DlARTEqfNafydpWZ2w==,type:str]
                client_secret: ENC[AES256_GCM,data:2XPlyAkMcjDorZoydm8D9b2EkWlXTGa6,iv:ar54+Eend6pkAGiF+NIyk+2Tp53UFxnpSmPya29gLFM=,tag:MxKsfWBf5L9Bg7k+X4Ey1g==,type:str]
                callback_url: ENC[AES256_GCM,data:Ufu2OC3h0OFpOWmizNUf3i6G1UfzXW1vLCmGDpUzzYompJyPpu1WvtT58UL2c1ZzEe02o/BedA83mQ==,iv:WJgh3QawjFBcuMQ0xH7yPnbbMwD+pNhtu6+ibaRyr+8=,tag:ba7N98ywuzndcRiEEDQYQw==,type:str]
            Authenticator:
                admin_users:
                    - ENC[AES256_GCM,data:1yK21AJ3tU23cjCNFF8T,iv:qgiRx1Yh+c2SwVAIhV6neNM6YxDYTwjEFhDD0pC1KaQ=,tag:HO1I/4vHuCdN8G4CPUjFQQ==,type:str]
                    - ENC[AES256_GCM,data:MW09w07cnNKwrY3sFAgBxjS2qHQNs7M=,iv:+Di4Nv/rjGFDBAKb3WB/dKgYfefRpLj2nP6bHx5J3Ks=,tag:j9DQq0Gxayx4TiuCswhelQ==,type:str]
                    - ENC[AES256_GCM,data:FN2AR3ypwD1O9RI/2DePaQj135IznA==,iv:MbqjW7KqM5Ge7AjMqbnffZkixDqyP1TVvzldzZIyRug=,tag:epRKbau1AEErFQSI6+FAfQ==,type:str]
                    - ENC[AES256_GCM,data:vMyuAMFpEOIPnjBQKmQ9F3WMTfvn,iv:s0xkimYft3LBSf4yEYD+BshNrGflNjdXNwXz8C7PrcI=,tag:PAFJWHcFN438GcwKRYLUHw==,type:str]
                    - ENC[AES256_GCM,data:3WvWcM7t1b19J8DSjh+1NChdJ2xAersf,iv:kBj4yGsMsj+G55cL3qXEnyd9xdmEclKGPYkrPTNbC20=,tag:2SJOeSlnWOkWmHhRln5Wwg==,type:str]
                    - ENC[AES256_GCM,data:+d/3/M6a2oxyDD8YNwO3uS3+9Q==,iv:ooSMwueOzbEAxGih9tUOi4Bv8Z95rvUoy60yP3B5Xc0=,tag:dKR31LfeF+qOvj5JgxZ+WA==,type:str]
                    - ENC[AES256_GCM,data:+2S0/TwkpupirLTgpiu8BkLQtg==,iv:uMHO1orsB+9+SMxRjLoCOYzAGtAXhV3C1bi1pAyMzYQ=,tag:dzZ3ok/JyD4z6Meso1QXGw==,type:str]
                    - ENC[AES256_GCM,data:jl4uC6nc8tdNvRbTRW+6UneqarhL,iv:bU9zXmyD0g9Yts7QyBYzh4fEPHKi5XSvo1NyvLwQ+98=,tag:q4kxovXIqejPJpFZn2UjKQ==,type:str]
                    - ENC[AES256_GCM,data:r6qv4KagE+sBC9iPxBmAf6o=,iv:3NeAkVgveQmgImFGO2uOKEPq/aAmUMY/Zzsj+Jx0DL4=,tag:+2VoXy86ei8xh+mbKvkq2w==,type:str]
                    - ENC[AES256_GCM,data:5N3D0105wOZ9JziIPMcmHr8mpA==,iv:4gej1rXrDcYpQRKgUEpSvFL39x/xElRQlmibDX9e5bA=,tag:FgSTcHNnhjsr4XvU2/oyPA==,type:str]
                    - ENC[AES256_GCM,data:hSqye3900TJkSytRcGQ4e9G1AXE=,iv:13aWsB2jCmIYHKQZffgzh0kmenLJ9A0DmwjoVM69XjI=,tag:vL4CrdYFO03W9GP0UfIyMQ==,type:str]
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:YquWtGQWZzBAcRP33Fpqxpg=,iv:q4NdhGr/Y7qDWcdU09cJfWXEEEQuKVS0A58CqV27ON4=,tag:dGKNuQBvmqS4Ka6ItRWzwg==,type:str]
                client_secret: ENC[AES256_GCM,data:ElmZKLv2zOFkmeunkAMpzXRHeEEuEQKnp9dxW2vf22iHFaXsbLC6HA5uOmmDyogLv61dqbfY/1i7e7ifP5hGBg==,iv:Ph7+fZRDv1mGsYawdFlMlDmwVSXHnEZgQl76nLNpD2M=,tag:h0Y+q4hSe6p5GzVuwloAuw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:32:23Z"
          enc: CiUA67O9AHqzT1SDT7i3kHJemupPJCBoFJI230TUk6FxQmH6MkC7EkkAdEnSzm0xvn8eZW4HMhezCNpXlUVjIPsCo4VsngTo9OxYvqJzcp4XBFndgMa2gq+4k3cjrO/edcwJF5EVJBBFqEBkPnJY8KIU
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:32:23Z"
    mac: ENC[AES256_GCM,data:3UHfefgPFzYZA4jAsBHvREtbp4cQ+InLJs24KaUlqNx8sB9EX/1ylmyTNR4AqiiLGUZnvG4QiWho3EtAF+L9q6lcva3nRmzJMCnAjgam8v2EZY4783oiNZK+bSBflN4u46DBvYZ43N+nakGC6GH3ITOzeiJrvUdCQ/SDSGYA1iQ=,iv:GFgvfADkRgqG9Z1OB0KKJZSoia/ylEPbNk4L4OQwuek=,tag:Y3Ep9EKi/WbGxdYtEVZyOg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
