jupyterhub:
    hub:
        config:
            GoogleOAuthenticator:
                client_id: ENC[AES256_GCM,data:yP5zEbs9nyPffbb1mg4FX3wtYSTVYX0D0tPuAnBrF51pzhvDklPfTLm2BeRil3Z7+0Uf+IajQWIRi9Lt3gToL9SuByqA72am,iv:LmfkkGYQCFe2VGLX1sNZWxBYX+lJzLby5S0zQG9Onrk=,tag:x3SRt1V3z9wrxKng6SUw5Q==,type:str]
                client_secret: ENC[AES256_GCM,data:US2GjG9iPyBiiiJfCJkpNGfeJaa31K3l,iv:eDGeYB5pMw+NqfGPL75SEjYKltVmb6aSLXP6qSuaMrM=,tag:A2EYqSxieXqBmLzao6hbAg==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:NQB8H/SzeNALRMAhYY/flZEQTJ8GkHsR1VVa3KuKeY0VZFpQz1kjmpqlUURbdLqLSlkBbqwRZ39Ag9GrcWYAueOn,iv:A+rsaUmaAnbt/XjtGIt3pJzroR8RsCX1xDom3w6x6bk=,tag:FdoeZ+2u5/mctre4xmZLTg==,type:str]
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:xONtZzN84yjbSLqXyonp+Ts=,iv:wIpWgxRt3F7xQX3mtGbCrMCVyBMAMD9+64YOT0Kn7CI=,tag:/umomjJGgE7f+s/b/5QmFA==,type:str]
                client_secret: ENC[AES256_GCM,data:WSvFaLoqPByzlTC8Q5YikzHbwtp9diMHmsDsmd01AC2wWZqxVIlfy2KGI2ZzMoLIYid/KGbCipJcUIjpfIj7zw==,iv:VLEfTakCZbyHGka+eTrZL3UCy0WUhvbmfFOdY7OQGs4=,tag:bXY13vTCNWLFpjfbKO2iIw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-05-08T23:31:53Z"
          enc: CiUA67O9ADxefAmu08sz6d5BJMDFoFOPsyEtQoWK0mQ8lkV+5NUWEkkAdEnSzrCiCl3CZItcmX82g0Ba26agOXSuCimZgwwq7d1wPkpeGxFV3y4Tytrvi15RnKrLxvqmiMFMNpwRqz+ugB/zRQeN5amD
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-05-08T23:31:54Z"
    mac: ENC[AES256_GCM,data:3F8ckremdECGPU2UKtCJLWkfCUhpgzITDG4NqnyOaMcdvKy+0jFvcGupwe+i7InCBGOT7xZZR/hICAb8VeIlkWzOXXFD2Iw5Jcqky1Y++4KbJC2tiV/x8Hb1/ZSKRZfn8IEN6D+gP3tZO5tNSNIti8b3gCpRHimaFiXVu+MUmqQ=,iv:jSDulW66TqixIVFVpegpcPdEBgvvPXYbD0cgXfJDbgE=,tag:ju4c+iCs++ZV/jXw6jUXJg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
