jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:UmAAnPaw91fEqTNGP/ByFbc=,iv:rJ97Aqv5HtJ39OgBQUg5zzzhrQ+dissA/uZU59us5eo=,tag:l5xm/7vtwZmEGZglfMAPrg==,type:str]
                client_secret: ENC[AES256_GCM,data:byB59aW3g4spzAHWIj+zd1k4FTSGAuHImWG+KNW6qybck+pzkjIYsmanOzRXFAncdGhPUUSWbgid6jO5KT2S/A==,iv:vCoYltSJX9rxMbDoipqcxtsNFj1QJViUF45vIkerftA=,tag:j1y2Wb08cqq9dmfaVsHcKQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:UGjEjtishHDt6RE3WBMPUFzBWqNVsNKLMIG0uLxUQqMM4ED1zjMv7c02Dhyz1M0ywyEcS2IuPg==,iv:tds0OhF5CQJR4pZFsM0Q2NQnbn49UyAkaZoqeKL4bYI=,tag:Rw/ocKcul2uizLB1JW6xJw==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:NTz5IyQDBPIUslhr,iv:CXwIHh0qJm/bjzSvQVXjkhGuW96uMLjDb+avGgPNWfk=,tag:pFQKRz3/Zw/V/XV2lvJEuA==,type:str]
                command:
                    - ENC[AES256_GCM,data:3nEl1jlSG9f4pLd5,iv:oZZOEpYx3kIzNLtZ7rkhUKkhMCpxnIhRuRtpgAkzdHA=,tag:A2qasYPGIeAz8ph741T0tg==,type:str]
                    - ENC[AES256_GCM,data:sp+knR2qN3EaKHu26ZTN9ZY6rlpwKRc6chI=,iv:A4D/Gue6ej/t6VuKR7zuoC6z3oDWD9hrKiPW0w5xep8=,tag:aW0MnVi/D8Hs0kq6/+hTuA==,type:str]
                    - ENC[AES256_GCM,data:OUHyILNFugzuIjCMnBlDmSjtsX35W1fPw4nCLmTGxEU=,iv:0zN93x3wRFI2Gsh1FeS8eZLF+XLQL2wXH2LL40jlGwg=,tag:NB/YtHQ/wUPtAsuDs/1h7g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:39:36Z"
          enc: CiUA67O9AIDdOKi6CO4pITeZ8qW0uu88LFnAeDU1NOCLh9MRWMW7EkkA1heVYTIeePxR1/rmVsadEIGQy9YG1O4hXClz5hkaIZ8rBa1j7ZNXUoG7IihFqjjuDmWdhhtjniFZkERgToeY/l6nWqp/O2E8
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:39:37Z"
    mac: ENC[AES256_GCM,data:8Hx3KuSgEdry27rwYpkY+cyWRuTIj2U5BDTsOdWYRXuP9L4eClfFqfTMgaWYLSwpMbvRWj/UG0pWAGMA4PCwvm8U7NzJfEA18uVwvu0mf9gnQE777VRWqInshcMz6S33opOSYTXvaoBH1Cc5H3iPcY/Wwli7U2kJUPs4j+rHMrI=,iv:ZfwTjQY1GRGZ5RXWrb9VFn9eMNBpp0DO23FroC7Y30Y=,tag:9X879NbB24iyoljrXPbU0w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
