{
 "title": "Activity",
 "tags": [ "jupyterhub" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "hub",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Activity ($PROMETHEUS_DS)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "PROMETHEUS_DS" },
  {
   "title": "Running Servers",
   "type": "timeseries",
   "description": "Number of running user servers at any given time.\n\nNote that a single user could have multiple servers running if the\nJupyterHub is configured with `c.JupyterHub.allow_named_servers = True`.\n",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(\n  jupyterhub_running_servers{namespace=~\"$hub\"}\n) by (namespace)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Daily Active Users",
   "type": "timeseries",
   "description": "Number of unique users who were active within the preceding period.\n",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "max(\n  jupyterhub_active_users{period=\"24h\", namespace=~\"$hub\"}\n) by (namespace)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Weekly Active Users",
   "type": "timeseries",
   "description": "Number of unique users who were active within the preceding period.\n",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "max(\n  jupyterhub_active_users{period=\"7d\", namespace=~\"$hub\"}\n) by (namespace)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Monthly Active Users",
   "type": "timeseries",
   "description": "Number of unique users who were active within the preceding period.\n",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "max(\n  jupyterhub_active_users{period=\"30d\", namespace=~\"$hub\"}\n) by (namespace)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  }
 ]
}