{
 "title": "User Diagnostics Dashboard",
 "tags": [ "jupyterhub" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" },
   {
    "name": "hub",
    "query": {
     "query": "label_values(kube_namespace_status_phase,namespace)"
    }
   },
   {
    "name": "user_pod",
    "query": "label_values(kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\"}, pod)"
   },
   {
    "name": "instance",
    "query": "label_values(kube_node_info, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage / Request Ratio Distribution",
   "type": "timeseries",
   "description": "Distribution of usage/request ratio. ",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(\n  count(\n    sum(\n      container_memory_working_set_bytes{name!=\"\", instance=~\".*\"}\n      * on (namespace, pod) group_left(container)\n      group(\n        kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\".*\"}\n      ) by (pod, namespace)\n    ) by (pod, namespace)\n    / \n    sum(\n      kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$hub\", node=~\".*\"}\n    ) by (pod, namespace) < 0.25\n  ),\n  \"bucket\", \"<0.25\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n  count(\n    sum(\n      container_memory_working_set_bytes{name!=\"\", instance=~\".*\"}\n      * on (namespace, pod) group_left(container)\n      group(\n        kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\".*\"}\n      ) by (pod, namespace)\n    ) by (pod, namespace)\n    / \n    sum(\n      kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$hub\", node=~\".*\"}\n    ) by (pod, namespace) < 0.5\n  ) and count(\n    sum(\n      container_memory_working_set_bytes{name!=\"\", instance=~\".*\"}\n      * on (namespace, pod) group_left(container)\n      group(\n        kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\".*\"}\n      ) by (pod, namespace)\n    ) by (pod, namespace)\n    / \n    sum(\n      kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$hub\", node=~\".*\"}\n    ) by (pod, namespace) >= 0.25\n  ),\n  \"bucket\", \"0.25 - 0.5\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n  count(\n    sum(\n      container_memory_working_set_bytes{name!=\"\", instance=~\".*\"}\n      * on (namespace, pod) group_left(container)\n      group(\n        kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\".*\"}\n      ) by (pod, namespace)\n    ) by (pod, namespace)\n    / \n    sum(\n      kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$hub\", node=~\".*\"}\n    ) by (pod, namespace) < 0.75\n  ) and count(\n    sum(\n      container_memory_working_set_bytes{name!=\"\", instance=~\".*\"}\n      * on (namespace, pod) group_left(container)\n      group(\n        kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\".*\"}\n      ) by (pod, namespace)\n    ) by (pod, namespace)\n    / \n    sum(\n      kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$hub\", node=~\".*\"}\n    ) by (pod, namespace) >= 0.5\n  ),\n  \"bucket\", \"0.5 - 0.75\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n  count(\n    sum(\n      container_memory_working_set_bytes{name!=\"\", instance=~\".*\"}\n      * on (namespace, pod) group_left(container)\n      group(\n        kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\".*\"}\n      ) by (pod, namespace)\n    ) by (pod, namespace)\n    / \n    sum(\n      kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$hub\", node=~\".*\"}\n    ) by (pod, namespace) < 1\n  ) and count(\n    sum(\n      container_memory_working_set_bytes{name!=\"\", instance=~\".*\"}\n      * on (namespace, pod) group_left(container)\n      group(\n        kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\".*\"}\n      ) by (pod, namespace)\n    ) by (pod, namespace)\n    / \n    sum(\n      kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$hub\", node=~\".*\"}\n    ) by (pod, namespace) >= 0.75\n  ),\n  \"bucket\", \"0.75 - 1.0\", \"\", \"\"\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\n  count(\n    sum(\n      container_memory_working_set_bytes{name!=\"\", instance=~\".*\"}\n      * on (namespace, pod) group_left(container)\n      group(\n        kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\".*\"}\n      ) by (pod, namespace)\n    ) by (pod, namespace)\n    / \n    sum(\n      kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$hub\", node=~\".*\"}\n    ) by (pod, namespace) >= 1\n  ),\n  \"bucket\", \">1.0\", \"\", \"\"\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "95 Percentile Memory Usage Across Notebook Containers",
   "type": "timeseries",
   "description": "\n95 Percentile Memory Usage Across Notebook Containers",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MiB" } },
   "targets": [
    {
     "expr": "quantile(0.95, avg_over_time(avg by (pod) (container_memory_usage_bytes{namespace=~\"$hub\", container!=\"\", container!=\"mongo\", container!=\"postgres\", pod=~\"jupyter-.*\", cloud_google_com_gke_nodepool=~\"user-.*\"})[15m:])) / 1024 / 1024\n",
     "legendFormat": "{{ pod }} - ({{ namespace }})"
    }
   ]
  },
  {
   "title": "95 Percentile CPU Usage Across Notebook Containers",
   "type": "timeseries",
   "description": "\n95 Percentile CPU Usage Across Notebook Containers",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "quantile(0.95, avg_over_time(avg by (pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$hub\", container!=\"\", container!=\"mongo\", container!=\"postgres\", pod=~\"jupyter-.*\", cloud_google_com_gke_nodepool=~\"user-.*\"}[5m]))[15m:])) \n\n",
     "legendFormat": "{{ pod }} - ({{ namespace }})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Per-user per-server memory usage\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (pod) reports double the actual metric\n  container_memory_working_set_bytes{name!=\"\", instance=~\"$instance\"}\n  * on (namespace, pod) group_left(container)\n  group(\n      kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\"$user_pod\"}\n  ) by (pod, namespace)\n) by (pod, namespace)\n",
     "legendFormat": "{{ pod }} - ({{ namespace }})"
    }
   ]
  },
  {
   "title": "Usage/Request Ratio",
   "type": "timeseries",
   "description": "Actual Memory Usage / Requested Memory\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{name!=\"\", instance=~\".*\"}\n  * on (namespace, pod) group_left(container)\n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\".*\"}\n  ) by (pod, namespace)\n) by (pod, namespace)\n/ sum(\n  kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$hub\", node=~\".*\"}\n) by (pod, namespace) \n\n\n",
     "legendFormat": "{{ pod }} - ({{ namespace }})"
    }
   ]
  },
  {
   "title": "Usage/Limit Ratio",
   "type": "timeseries",
   "description": "Actual Memory Usage / Maximum Memory\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{name!=\"\", instance=~\".*\"}\n  * on (namespace, pod) group_left(container)\n  group(\n    kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\".*\"}\n  ) by (pod, namespace)\n) by (pod, namespace)\n/ sum(\n  kube_pod_container_resource_limits{resource=\"memory\", namespace=~\"$hub\", node=~\".*\"}\n) by (pod, namespace) \n\n\n",
     "legendFormat": "{{ pod }} - ({{ namespace }})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Per-user per-server CPU usage\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  # exclude name=\"\" because the same container can be reported\n  # with both no name and `name=k8s_...`,\n  # in which case sum() by (pod) reports double the actual metric\n  irate(container_cpu_usage_seconds_total{name!=\"\", instance=~\"$instance\"}[5m])\n  * on (namespace, pod) group_left(container)\n  group(\n      kube_pod_labels{label_app=\"jupyterhub\", label_component=\"singleuser-server\", namespace=~\"$hub\", pod=~\"$user_pod\"}\n  ) by (pod, namespace)\n) by (pod, namespace)\n",
     "legendFormat": "{{ pod }} - ({{ namespace }})"
    }
   ]
  },
  {
   "title": "Home Directory Usage (on shared home directories)",
   "type": "timeseries",
   "description": "Per user home directory size, when using a shared home directory.\n\nRequires https://github.com/yuvipanda/prometheus-dirsize-exporter to\nbe set up.\n\nSimilar to server pod names, user names will be *encoded* here\nusing the escapism python library (https://github.com/minrk/escapism).\nYou can unencode them with the following python snippet:\n\nfrom escapism import unescape\nunescape('<escaped-username>', '-')\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\n  dirsize_total_size_bytes{namespace=\"$hub\"}\n) by (directory, namespace)\n",
     "legendFormat": "{{ directory }} - ({{ namespace }})"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "timeseries",
   "description": "Per-user per-server memory Requests\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"memory\", namespace=~\"$hub\", node=~\"$instance\"}\n) by (pod, namespace)\n",
     "legendFormat": "{{ pod }} - ({{ namespace }})"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "timeseries",
   "description": "Per-user per-server CPU Requests\n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"cpu\", namespace=~\"$hub\", node=~\"$instance\"}\n) by (pod, namespace)\n",
     "legendFormat": "{{ pod }} - ({{ namespace }})"
    }
   ]
  }
 ]
}