jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:YA/mpMDYamqQ9AJ/vxvFb24=,iv:qpglFwgQfKDik5MRnt1ORTV45LP8SpXvqY/eJ8G6lcU=,tag:O0drc9EFxWsVYyC+azWvhw==,type:str]
                client_secret: ENC[AES256_GCM,data:T8E9SlMbceIlJQEB6O/7JA7hpQCu9o2/Q5hdPGLUfI/0bNWUxtfAnWTV5QtQ8/xnwayODBzo7Tc2TrfzqTs9ow==,iv:CvXSLJLFeA11K3LCIubjm/8amqN+o7ZjXr5gsIxWxlo=,tag:ctuFEnmVXLEiNla++I/HcQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:1JNsw3HtvpZso2ThLQkaYz/ylQ4iP6WQhhNzqqbGFbNXHSC4zchVq+PM91GrUlLwzpP8,iv:o9W0lLiW76TVpN0dNDmSQZM4T7pDqv3gXpOc4SBj6C8=,tag:+8NoysYCeQ4Er7YYH5i4DQ==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:ZhN6qHkNuA5yNHB8,iv:gti1IzxsVBQ6IfHQJ9sRlsR05RkIxEEB2tSjU3z0Ulw=,tag:71Mzg4Y7yEjqu0AdKjc76Q==,type:str]
                command:
                    - ENC[AES256_GCM,data:LLiznLMIkjHdRf1E,iv:tDMbliX8q6c1R/5am5ZWEOoKD2LyncIZH4ZNIzqwRfg=,tag:txa3TQiRzmZ3iAKd5dDAAg==,type:str]
                    - ENC[AES256_GCM,data:ZPqJva0M2Fg2MR7qfzhNrr6PtVkzGoAEJ04=,iv:ZH1307KKjhv1fjBHua9KTuBFmJPO5Zfz61ja8SF5oNs=,tag:/XlkcInwuURYlPxekCHu/w==,type:str]
                    - ENC[AES256_GCM,data:Iqpa8H+6djktCSS/UOZ3vHN1gP02PPjvoF7Of1kX3II=,iv:pPsZyMWECFkY6GERn7I2kl72DtUEXf99PBpQBNGsQBs=,tag:enZARYVBVryrBVYDf/qtqg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:32:57Z"
          enc: CiUA67O9ABdJp/W0A0e/qvfDENHyRu5WK3dwXTbI0Q0GIKHtMZ6iEkkA1heVYT9FrDWiz6w3PUaipV5irbpi+M7jOnm1Ie4pjYqddVqtra9A/svRVcVUG0JeigWBDXoyTRN2CeoJURvgQsGwg717Ncyq
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:32:57Z"
    mac: ENC[AES256_GCM,data:qz8sd6cOKb9G8hap2Uo3hnCh+HFfSTi7iePrTTJ0c099lkE/oRRmLEehtlzUyF4Le/vlfYkPAMTnxpRg5lSxumclV1T2Qc+hG/E4Rn4S4jUZsPOOeoi3Pmwyi3KxVUDYofmHapO7yg4DAy3aoIAYvP6h04OF8O377tfCKvmv114=,iv:i+4cULqFWiLEA0Og3zijawDHZQF9yjK2kDAkx1Q9wa8=,tag:tQxs33vzcFNT9IuXceJPzw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
