jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:UrY3Q95XkzlnDUMD/4db5+Y=,iv:HYe8IseA4K6o0oNl9duVW0FYbzqh8cBLOhD4GLKHn9c=,tag:qvZytlxLIXF4/U5OWCfxTA==,type:str]
                client_secret: ENC[AES256_GCM,data:43kVDQIwaj5ecVfYkM86tRcZhZ3agnjl4u7yLkSrUz4VgpXtWg1MqKvINFBEO1KnnWNKpNwUs59t83jy4cUoXw==,iv:28dY9NYJxxtwDbWX9UYKcMKHMDM0P/WSUoX2guHdZJI=,tag:uVkDdbIhGiE96DImT3mvaQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:somy57KDSkcozagu7CwHQEk2C0rL04fzhM2b0ORJylXDwkZbSNz0CA7m1F95nVetSITWvaVB1pQYZgaFHsI=,iv:er+cQ/mojhoE+5fJ78Jpg5crgaD7RpBXveBj64D2IGY=,tag:EkUNtIVFJFFAcxlEfbogSA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-02-06T00:43:09Z"
          enc: CiUA67O9ADZwPxDznOlr/FBc3Tqj/5US92CtGFQ7NczvG8PigQd3EkkAxMHsvCrN7Ej9Dqe/W/PRbSMAICB3aR7XU7r6wAhuYfOFtFUP39JMpMfU5KtlBDM72ZYOavC8VVN8GJKMe4HjOkh6QPNlDCaG
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-06T00:43:29Z"
    mac: ENC[AES256_GCM,data:B7TBragR39pBNw+w/idS6gcZL/U/OkHMf7SSX9e5Qc1rBYML2sZEMk/ArfHIAdpfdZ9T5NAK6EWOa9E/eE19+7s6vJ2dQpGrTP1ogFLQ1BNma/8PFQE/XqDUrejfTQmn2cw1vcgBm2MVvkRNTUcSgwMSAKZLOJ88upGXr1DvBmc=,iv:vhH08kOhtMCaMrD+yEHyDi4diYXyCMqUSjSKm+Uw+rQ=,tag:R72sGDE+4ZtrZc+DVwlxgQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
