jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:RwwBb8aGresMr0aTxopdPeo=,iv:I7cjLKhNAOX9nCDCVgQ//iAmWsqLN9WX0uaaujD7YWQ=,tag:6x7MUJwupqQBguhz78uYyQ==,type:str]
                client_secret: ENC[AES256_GCM,data:4kZMP0+SVTjSLbRl2J2o5L5vJQEcMKDWYztWnq6MVJ8cGXllx/qiKOgFx/6W0q29gN5Y9HtQLuPeQHIjKqmJMw==,iv:QGcZ3s0RGx2sFLRz/5bzoDY3Vkp3+/C8+YG3+BsVIko=,tag:kNipaxFxXwGc0pHPkXjNxQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:somy57KDSkcozagu7CwHQEk2C0rL04fzhM2b0ORJylXDwkZbSNz0CA7m1F95nVetSITWvaVB1pQYZgaFHsI=,iv:er+cQ/mojhoE+5fJ78Jpg5crgaD7RpBXveBj64D2IGY=,tag:EkUNtIVFJFFAcxlEfbogSA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-02-06T00:43:09Z"
          enc: CiUA67O9ADZwPxDznOlr/FBc3Tqj/5US92CtGFQ7NczvG8PigQd3EkkAxMHsvCrN7Ej9Dqe/W/PRbSMAICB3aR7XU7r6wAhuYfOFtFUP39JMpMfU5KtlBDM72ZYOavC8VVN8GJKMe4HjOkh6QPNlDCaG
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-06T22:24:18Z"
    mac: ENC[AES256_GCM,data:4dDo5/YepQBfzz0NDNeza8RvHFqIPkLa5d/JZBSzCbwB1e9lfoS1AX83WBv9a3gC5Dq1/IcfgyD5p7BwZEChROiB70oCtJPnrK3TNnlnG5AEz7xcJ8BHRFXvmPvEdKf9qNoWMqcQ1jFEWcmSiRPqASc/EAnrXf0NCo+dvQxRSXM=,iv:gmQVtF74qgv4kPCjzgMxymYkavaIM5Go/e3rdhUmXvQ=,tag:nNSdPLOCoRWOmUkKw63M2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
