jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:/VedfPLyL+Rj3gciMxQ5H84=,iv:WZsC/06SEfEEeH4/NY+txGypgP/lShrJLc8DVXS7tco=,tag:kdZCzktRscuCYz4nRlkxTA==,type:str]
                client_secret: ENC[AES256_GCM,data:EqzXDvAIMyGeTnGjUDOg6X6XqSwDmogtz/HXhc2LNYMhoSgg8PSUqvEFNUNG6w59tkRXPerBR6PyOuG31ftYXQ==,iv:D/rf3aWams6O2NcmdjFYxEVV5dQoWv3ubZ1kTN5KMO8=,tag:/LLaEHP/RB17Td0UW1I2bQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:8BmkBWJKxZmbKHVqJT50obT2D9RdQpEOCw9plqhZDyUeh7uiJVG5y5guXdiO+0MvwKIoXAQbz2z9zZq8Mk0=,iv:ZwPIuR/dAfY33smRpzlu9UZu9/Xu2z9hhpSTINd0Vpk=,tag:mpDxFk77V3Hp9JoWFvoo+g==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2021-05-05T10:57:58Z"
          enc: CiQA67O9AK2027WGYGTzywa01Cz+Ez7sOTk/d9payovyK5pg8g4SSADmhpq89bbIWFjlGg79o/iupJ4anLU5Ab9VL+qNzhu6e83JtJ7wSv6sK+cDiEfVSaKQ1YIcadDXFt4WUKRt7MFvAa1sLqp2LA==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-22T23:27:26Z"
    mac: ENC[AES256_GCM,data:qb/TlQuC0eEqE9q8W/SyUNl6qdI0j1KsKNFa+jGGHdP7wpPrIfgVLEaBgq8cEUDRBpBcRlfXDN5eDlAy68PtOlPMfX4ZwwuEvmWjM7NHNV4YYb+JJ4FOB9PtZCn3VqBuvYFB0bwZTppRC0aNc4QTDancDXz4Q005pBsq+r+Npk0=,iv:lWue6Dp1XRALy3/1x+FjcFeJOaoz5s8zGhecp3gzPWY=,tag:2f/d2btNncS3QRHXjgj7ng==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
