jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:m6YBe8UmbAaKRcu1p42ifWE=,iv:6t+Rlxojf/RGzUllmiLZpi7foWP97bO7fj2rB/72bGA=,tag:z8Pw+glEP7J3gfh8/gKAfw==,type:str]
                client_secret: ENC[AES256_GCM,data:1XpvOV4wiyRkAxwgYvF7sPQZwvW2BqmvMkBuVuNBC2K88PVwrOn+ufoUkP3P4gdJaX9J1L9kGjy0oRqkMpMvyw==,iv:XN00Vq6JhXkefRs61Uk0IH9VE3mIpQEG9FCeJ+dzis0=,tag:FIYB7mbdE0o0ttUUD2JDLQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:MM1bu2dT6kK3VLCRE0aXPEZ6a9K+wZTlcIScpynM1g3KgyGeqRqV0NkX0fDMWbsnTv7ZpE4=,iv:P7LxxketbWxG8ZdIsjSKRia3soaehliKJPMopMC2KT0=,tag:xGZMI7OdmyOoxl8DyaMy7A==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:WAh9lRsBNAlTBDyz,iv:jMbuuAumObTBH5yTacLfx0PBGhyb7C/WhMKesuRzPPE=,tag:WBAQs4Z6OmJU0yCnG7K+Jg==,type:str]
                command:
                    - ENC[AES256_GCM,data:dyWyy08uoT9Zjx5O,iv:vRQt6gro7uIGcLYWtCjlzewBTjiMi/mEaAYFAhc21oE=,tag:RS1fugtznEI5MZHlquaoAQ==,type:str]
                    - ENC[AES256_GCM,data:7ITqyKhm5Anw2noilFCwrq6zwEv1LHzPY+w=,iv:vH2v3YrAZkzHOqlpZecnxLS3zM35a4ZlySDo4vLB/JU=,tag:XNuQ4zTbT6BkwQhCMqpqkQ==,type:str]
                    - ENC[AES256_GCM,data:mfrNF5trFgow9tL75AvPwYiUQcRYmaYJ2U9BTPXek7k=,iv:QhkcPMFzEZ6/7lQwz8P1sTXYqkFlsCjK3Fn6ediHxnw=,tag:oouFdnGYlAXL6qLU/VsjVw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:37:47Z"
          enc: CiUA67O9AOGAjCzlIy9K5d95MzP/eJ3iNkb7PTypdGGT+Ox3Xdn2EkkA1heVYVM+1Wc2J6iSa/SQDW+ry4fE/JsFlSjN4Sv8FkBN7LEIqOXzPfA97k4d1cbaWtKaQQa4F+K+z6mjUEvY8vbDT2wjgNvd
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:37:47Z"
    mac: ENC[AES256_GCM,data:GZ8Zp+efqplwzsNSFkaVCnBwX/4H9ZFCzQ5p3Tk1kT/XaOm8TcY1ApeVcirycFxDQufQqtG1iDSiAyGnIiFmmoJ//2tEuGCqc8EqCokIIBCHd445RUxWMIShJwpIo7JrELVblT71M61XGR7g16g6l8GeL/hSa0gtY7u49B2S4NI=,iv:kxY35f41YGscZ+DxI5eObm1gggMLCGmpQDKS6pyh3gs=,tag:byuDevjd8MBULeFKNbCBgg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
