---
title: "Customize the Hub Docker Image"
aliases:
  - ../admins/howto/rebuild-hub-image.html
---

We use a customized JupyterHub docker image so we can install extra packages
such as authenticators. The image is located in `images/hub`. It *must* inherit
from the JupyterHub image used in the [Zero to
JupyterHub](https://z2jh.jupyter.og).

The image is build with [chartpress](https://github.com/jupyterhub/chartress),
which also updates `hub/values.yaml` with the new image version.
`chartpress` may be installed locally with `pip install chartpress`.

1. Run `gcloud auth configure-docker us-central1-docker.pkg.dev` *once
   per machine* to setup docker for authentication with the [gcloud
   credential
   helper](https://cloud.google.com/artifact-registry/docs/docker/authentication).
2. Modify the image in `images/hub` and make a git commit.
3. Run `chartpress --push`. This will build and push the hub image, and
   modify `hub/values.yaml` appropriately.
4. Make a commit with the `hub/values.yaml` file, so the new hub image
   name and tag are committed.
5. Before the deployment, disable the gcloud alert for the hub.

Run the create_alerts.py script in https://github.com/berkeley-dsep-infra/datahub/tree/staging/scripts/hub_alerts

```
python3 create_alerts.py --disable_alerts --namespaces <namespace>

```

6. Proceed to deployment as normal.
7. After the deployment, enable the gcloud alert for the hub.

```
python3 create_alerts.py --enable_alerts --namespaces <namespace>

```

Some of the following commands may be required to configure your
environment to run the above chartpress workflow successfully:

 - `gcloud auth login`.
 - `gcloud auth configure-docker us-central1-docker.pkg.dev`
 - `gcloud auth application-default login`
 - `gcloud auth configure-docker`
