nfsPVC:
  nfs:
    shareName: shares/nature/prod

jupyterhub:
  ingress:
    enabled: true
    hosts:
      - nature.datahub.berkeley.edu
    tls:
      - secretName: tls-cert
        hosts:
          - nature.datahub.berkeley.edu
  hub:
    db:
      pvc:
        # This also holds logs
        storage: 4Gi
    loadRoles:
      grouper-sync:
        name: grouper-sync
        scopes:
          - list:users
          - read:users
          - admin:auth_state
        services:
          - grouper-sync
    services:
      grouper-sync:
        name: grouper-sync
        environment:
          JUPYTERHUB_API_URL: http://localhost:8081/hub/api
          GROUPER_BASE_URL: https://calgroups.berkeley.edu/gws/servicesRest/json/v2_2_100
          GROUPER_ID_PATH: edu:berkeley:app:datahub:datahub-nature-users
    
  singleuser:
    storage:
      extraVolumes:
        - name: conda-shared-instr-prod
          persistentVolumeClaim:
            claimName: pvc-nature-conda-instr-prod
        - name: conda-shared-stud-prod
          persistentVolumeClaim:
            claimName: pvc-nature-conda-stud-prod

  custom:
    group_profiles:
      course::1546503::enrollment_type::ta:
        extraVolumeMounts:
          - name: conda-shared-instr-prod
            mountPath: /srv/conda/envs/shared
            subPath: conda_shared/1546503
            readOnly: false
      course::1546503::enrollment_type::teacher:
        extraVolumeMounts:
          - name: conda-shared-instr-prod
            mountPath: /srv/conda/envs/shared
            subPath: conda_shared/1546503
            readOnly: false
      course::1546503::enrollment_type::ta:
        extraVolumeMounts:
          - name: conda-shared-stud-prod
            mountPath: /srv/conda/envs/shared
            subPath: conda_shared/1546503
            readOnly: true