jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:YaAujoAHDbs/rWFjaWKSjZ4=,iv:aintm/j2GXHimBlyN7zwr5Nx4vnD1aYi3o7emTXtIcc=,tag:jC7vpJxek0pVHxJzyFS9Ng==,type:str]
                client_secret: ENC[AES256_GCM,data:7mg90o8gt5aBQa2CO+n5MS9NtRxz7TJTxtGqRjL2tbyqekG+QVEi01QWfPVHsRtQUXODcm0Z1aR2TX/+9Dm0dw==,iv:eOUcdDCx5mc0sI8tPqHl9y74UCBEhwEWCt1UdO9E7tc=,tag:QdUgH1KYBuO17731SVKgSQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:yUtlKP3/vrzNZJ8p1YgUajLEY9+yTzWn/d5cW4Ht8sv7EqCm4giE14XIqMvyJU5Rwy2HU6mAwA==,iv:wqqLubbmDNE/HqsBK9R/7+g885u70z4+1yH/Vil1JzQ=,tag:FaOs6KUgnnao8JheyGpCJg==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2026-04-21T21:28:41Z"
          enc: CiUA67O9ABwkiewUljo+g6BaFRhYNalLY7aZV1OfxK1Y8ye8dK5mEkkAdEnSzp9pB3X4y9uwaXbFvPi9EuZyYX46FJwp+lY37utvbU6Sajm8807rYng2RyIAeZdfmNpIW+78QS36b4QzGhcqNVRYAAFH
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-04-21T21:28:42Z"
    mac: ENC[AES256_GCM,data:xBurv1bfaixXW7uklx3gYlBan0X1PxgFpAOTyImIFiND3ET7v/TNsKHCZk1ZZnZAtQHMLd1wQtEc985ovgv02TnQvHQ2K5TfR940L3ln6WQgC5HOWfvOLY8LkbZwQuO25pqwzeQR9fU9RDSelnI/AJOIpXzn+NEJ/Jbb316/INQ=,iv:eGMlhS1bs1Iao6WMucHUc/SwKfhUyIAZzVmQaosb37k=,tag:jHmg2l4/iC/Houce6sTfsA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
