{
 "title": "NFS and Support Information",
 "tags": [
  "support",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "NFS diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "User Nodes NFS Ops",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(node_nfs_requests_total[5m])) by (node) > 0\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "iowait % on each node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(node_nfs_requests_total[5m])) by (node)\n",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "NFS Operation Types on user nodes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(node_nfs_requests_total[5m])) by (method) > 0\n",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "NFS Server CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{job=\"prometheus-nfsd-server\", mode!=\"idle\"}[2m])) by (mode)\n",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "NFS Server Disk ops",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(node_nfsd_disk_bytes_read_total[5m]))\n",
     "legendFormat": "Read"
    },
    {
     "expr": "sum(rate(node_nfsd_disk_bytes_written_total[5m]))\n",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "NFS Server disk write latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_write_time_seconds_total{job=\"prometheus-nfsd-server\"}[5m])) by (device) / sum(rate(node_disk_writes_completed_total{job=\"prometheus-nfsd-server\"}[5m])) by (device)\n",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "NFS Server disk read latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(rate(node_disk_read_time_seconds_total{job=\"prometheus-nfsd-server\"}[5m])) by (device) / sum(rate(node_disk_reads_completed_total{job=\"prometheus-nfsd-server\"}[5m])) by (device)\n",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  { "title": "Support system diagnostics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Prometheus CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"support-prometheus-server-.*\",namespace=\"support\"}[5m]))\n"
    }
   ]
  },
  {
   "title": "Prometheus Memory (Working Set)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"support-prometheus-server-.*\", namespace=\"support\"})\n"
    }
   ]
  },
  {
   "title": "Prometheus Free Disk space",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_available_bytes{namespace=\"support\",persistentvolumeclaim=\"support-prometheus-server\"})\n"
    }
   ]
  },
  {
   "title": "Prometheus Network Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"support-prometheus-server-.*\",namespace=\"support\"}[5m]))\n",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(rate(container_network_send_bytes_total{pod=~\"support-prometheus-server-.*\",namespace=\"support\"}[5m]))\n",
     "legendFormat": "send"
    }
   ]
  }
 ]
}