jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:TEOdw+l0J6slxrnhh9H90C4=,iv:Cn0qs4RvI1BmbXSriFBJUrsUl+MJlIAd4BAxTMLK/3M=,tag:cIQGI69nSXDAYLC061NFgg==,type:str]
                client_secret: ENC[AES256_GCM,data:5W+RjjIsBS53qLUSiATDvW8c444Hiy3w8o6JPCLcSEwUWHVm3EqmiO/Lzu1q4bJLM7kozdb2cgwE4NRG/5/Y4A==,iv:Xz5DFCcF1f3zg4d/FQhelkR5ZiD7Dy5l8a3Xn5qGZ44=,tag:PsZ7WCG7YHcWYmdvkgRY2Q==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:z6aDn51+SyzG++Sa0c3TXLqN3Y1+8n/6pISbV60KpO9b7pU+k7hyS1agukPtHU6YUlTrCA==,iv:PTbSmsOiLoVqPDim8z9f32mCAgTvV9nCEPd+9kAxzAw=,tag:HQM2Nj6hIN22sA0xrjkeLA==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:VZPziwyzRso1nfnX,iv:v3Dx6R5TRJVfE3iZ3EKPOOdPZ3WnBXWYqDYF+blUC/Y=,tag:Axr9VgaIFckpbFvD8m4P5Q==,type:str]
                command:
                    - ENC[AES256_GCM,data:jETzft6Jt1Lhfj3H,iv:lF8nWGN2fDBEgtrvDB/YzL7KOddeFMGoFdQmeAO9/mg=,tag:/5R3IZ3Cc1SI5hCRjPwPpg==,type:str]
                    - ENC[AES256_GCM,data:0zQwbmJ4c0SqNCme6cL1EXqBS96Z4vdTWnY=,iv:oCc4h8ut/U70E6xbiZu6DY/oUdwozsJpIEShmhZLboU=,tag:Vwj0iddlg1cg9TfvlumBZA==,type:str]
                    - ENC[AES256_GCM,data:VQdWRiuoznCiroTJ2A2Qnea1xjofjg5FsSJtQJi54mg=,iv:qZcrwZyJk2CobuYbmCAFOQ0pspZHD5G7i2yeFyuh6Z0=,tag:gFecQ6p6YTLt49OHhZPTGA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:36:31Z"
          enc: CiUA67O9AMwckQvuCiaitj2bP1gwJSXAR1spTiclboRHQ2bDUocXEkkA1heVYdLiKAx0a6ZjVx4DfVMaoOHDpK1lmgXDga0mQFG0JI8hJdO5jP8neJ3Kg5YCeYML6kzQgzgmaQ0LAMzlCeTv8qf4l1an
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:36:31Z"
    mac: ENC[AES256_GCM,data:QYTcYc2jNH+2DKyEGgZhToky54o+xxcW6SGhTZs9aMJ7jTbi+r8OarOYz7JtyNzSwIclFC0w96PNxIbXspDiXyqZbRxXkMj1xy76UDBgynht0CHwN4rRd6/EcibWDvFoU/2V2vHhzEAwg8leZPHzKGzZTlivBLQ7DvDW0Z5aM6M=,iv:23VeOqMuDMIgqJzkwq2gQVTFTvxYxJoDvkUsFuLE/co=,tag:1TPPpPO7/Pmf+dNvg68N/A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
