jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:5WCXJ24ekRT5UIZNnJZq7dE=,iv:fTe0iB5Mu7XD/vOKFweffq0CZbjtCgsprz4UPjUqM9I=,tag:WjyPmmkRDSM/nrldce3Nrg==,type:str]
                client_secret: ENC[AES256_GCM,data:AkFxEHxDf9UFxlY8X0PIyCApOkIVQ0pQ5vb1GD/udzoU3hhAEDdJpoJ4Act8bDq0akpSxzM2MCy0OjfeJBAbAA==,iv:M2fnJx4hoYxnRzCFIyiOHIs45i1ZWJBVb7ts8rgkpzc=,tag:MhJ7GHgHsoZsLyRLHsJogQ==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:UftNVZF3sMDISd6pNBVchGiUoJ7XyxOTRT96VHQ90g+lWM2zx7020yNQaBr+WmG/Sq2x,iv:WElb242xZK0L2wOUm/EyPr2BhP2jZk48nO8u8Ek8MEI=,tag:eL4gxeVFZ9Nqwq+Whj2vjA==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:d2jP5ulkpbyyxn1s,iv:plA/frt8aUBQLdItfIERJQuJbXTU5C6uE374K3VQHqE=,tag:EMwgeRKAnRhv6D71bAxtFg==,type:str]
                command:
                    - ENC[AES256_GCM,data:JqRfURe11K/bNOt4,iv:AI8fQ89OzF8r6gwGqHkVkVJhSAkA+aDEqoK13O89Fos=,tag:r600NnBYaFoUS9/lsAa3mg==,type:str]
                    - ENC[AES256_GCM,data:h1mc8DFgwiQ0sdes5TZ1YbwGHcj+BHuw/sc=,iv:SOHULbR73LsJ3pTaDQeoo3mZzlaM0IdzwHoa5ixElSk=,tag:LTo2LlmHoWcRQMyfhkgNLA==,type:str]
                    - ENC[AES256_GCM,data:YMC//Kr5ijtTFhCOIuqFgfkBWkpEAmj5O2/9AFKKq7c=,iv:C2yxWkO0bThOj/IHEAZ+MESv8ux5chKay53bzmDO3O0=,tag:gVvFBb+B3pouAQuiZbEfEQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-23T17:15:00Z"
          enc: CiUA67O9AMxnPCzlA9ehbwJDjVeDIZvCH9iuKqKd7E3SoJPkucCMEkkA1heVYREatAkUtjzpDCCQxLECgQEftn5942sgrEgj3CbuVR7XJ4jfDK16YXQh9IX+m1Av5gHHao0BPBw6N+PjFPfacq42jSBv
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-23T17:15:00Z"
    mac: ENC[AES256_GCM,data:c5uvbN6sDmMZ9z6aXcHQAX8vgnlG07OLbROjmzJnDLOEzYu8bYOZUdjlvf6LGLDUAKgbBBTkv437sLMU4Xuo2p+FcJylpLUlq97qFsiMnGfg3ObE6FMwwknwIWRxS8HJpVPTHGgLmWjBVS/E3kY9BG6IDRHWUIHR6IYRXzxkqpY=,iv:aBueHzSm546uJ6Z8Ryor88lzrEsBUoTBK+PjnhIhmSE=,tag:/YyKk7aUaS7fQCqmDCxHBQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
