jupyterhub:
    hub:
        config:
            CanvasOAuthenticator:
                client_id: ENC[AES256_GCM,data:6niGEokm3mjNi1W13FV0OJg=,iv:Dt0TEdAywBqUg9g6zrF1yeeZdIQ7UJqXJzpRxFGumGo=,tag:eIBDe3ZcGA372rK5kzwYHw==,type:str]
                client_secret: ENC[AES256_GCM,data:0A3v2DHYg2O7v31O7MdTCqMV58CCzbS4xGWJgLUxsFLeQ2gOKGPAottbLMD3VTWiJCKA7XKlD+Jlb7ejq7lP+A==,iv:fusDIHQoJ9729XqjYm8M82dFR2imf7km6dvCAzEtKHg=,tag:RdWplBb5tl6aYeKW3cFR3A==,type:str]
                oauth_callback_url: ENC[AES256_GCM,data:hJfsE9puf4EUEAzrCNO7jmF4SdXVlItxL4ZtFIliNhMKIAPoSNB/gbG5FVjVtJoHkOFEHAm1Ng==,iv:VPlxwaMeph8XEzLUNUrw5p/YbO0/HQ3XlbSWOoLBEgM=,tag:e8jPjNV+VcnGf/r5/bXCDQ==,type:str]
        services:
            grouper-sync:
                name: ENC[AES256_GCM,data:Lw5XjGt6x64z5mO1,iv:TsE8F8SyzgaWfJYT+fUFEf8WFdznKW1oz4IweTDjxJA=,tag:7TohXtzIyNeEK/nCORHdtA==,type:str]
                command:
                    - ENC[AES256_GCM,data:gTEMA3yHYCOmBaV4,iv:fuuUP7j1gpL0GazhLlfnpmSvCVMRtH+dbXw9VJc0jMM=,tag:Dx3Pii1aJrsL3gyNUq4m9w==,type:str]
                    - ENC[AES256_GCM,data:JG5hOb9E4VGW5m/lZeTPhhzfA0ekVWUhwHQ=,iv:FfW0m2zKlYp38eNy11L7IVeNhK4g8mweEem9Xw4hhz8=,tag:yYastwePnlPkL5Kt0kZTmA==,type:str]
                    - ENC[AES256_GCM,data:kAi7HiMzmgI7tA0rPLEpPPJXLDaiBknfDba5QrswmTw=,iv:+B27KM6QasdU5ax2gC19KPK19ZJvNHjbJyO+pJ2Wu3E=,tag:PC3PpfsBbBTU7lUMpZOi0w==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ucb-datahub-2018/locations/global/keyRings/datahub/cryptoKeys/sops
          created_at: "2025-04-24T23:37:30Z"
          enc: CiUA67O9AMFx4elUGiQkxxwkae2TuNRfYLUaLYjh+1Iv2R0P8aLmEkkA1heVYcZCFzZ+ZdxN4/0zDf7+2M/f+SOJG3Uj/9tfqJVdbD6k3uupZrtH23CXLnuvWYuKa+xIgFHW1xWdd34gyXHH9HGMik5d
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-04-24T23:37:30Z"
    mac: ENC[AES256_GCM,data:KIvntttwK01hAwSF5lpD3ABeqIOH3sUimrMdBKGFe4tKPgIKuN4GshZqMRBiPJzjuatA3zd6BasuZYhSg8jagV46mwWKwEgAVBIPo/dhryntZHHwiRNoMuL6xpw+76hhe6UiXcQ6D/5V25vg1DSeKW6p+tIJXryO1NSPL3GinCU=,iv:IJ2yBPAJFw4JvaJb0C3IxxIrQdwnC03Mw/GiQZFGZhY=,tag:KoxlYbGLydDxgUnZq8id3g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
