apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: test-webhook
  labels:
    app.kubernetes.io/component: singleuser-server
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]
