apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-webhook
  namespace: webhook-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resource-webhook
  template:
    metadata:
      labels:
        app: resource-webhook
    spec:
      nodeSelector:
        hub.jupyter.org/pool-name: support-pool
      containers:
      - name: webhook
        image: us-central1-docker.pkg.dev/ucb-datahub-2018/testing/webhookapp:v0.0.9
        ports:
        - containerPort: 443
        volumeMounts:
        - name: tls
          mountPath: /certs
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: resource-webhook-tls

